/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAvisosRouteImport } from './routes/_app/avisos'
import { Route as AppCitasRouteImport } from './routes/_app/citas'
import { Route as AppDuplicadosRouteImport } from './routes/_app/duplicados'
import { Route as AppEmbudoRouteImport } from './routes/_app/embudo'
import { Route as AppEquipoRouteImport } from './routes/_app/equipo'
import { Route as AppExportarRouteImport } from './routes/_app/exportar'
import { Route as AppGruposRouteImport } from './routes/_app/grupos'
import { Route as AppGuiaRouteImport } from './routes/_app/guia'
import { Route as AppPapeleriaRouteImport } from './routes/_app/papeleria'
import { Route as AppRecordatoriosRouteImport } from './routes/_app/recordatorios'
import { Route as AppProductoresIndexRouteImport } from './routes/_app/productores/index'
import { Route as AppProductoresIdRouteImport } from './routes/_app/productores/$id'
import { Route as AppProductoresNuevoRouteImport } from './routes/_app/productores/nuevo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAvisosRoute = AppAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AppRoute,
} as any)
const AppCitasRoute = AppCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AppRoute,
} as any)
const AppDuplicadosRoute = AppDuplicadosRouteImport.update({
  id: '/duplicados',
  path: '/duplicados',
  getParentRoute: () => AppRoute,
} as any)
const AppEmbudoRoute = AppEmbudoRouteImport.update({
  id: '/embudo',
  path: '/embudo',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipoRoute = AppEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AppRoute,
} as any)
const AppExportarRoute = AppExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposRoute = AppGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AppRoute,
} as any)
const AppGuiaRoute = AppGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => AppRoute,
} as any)
const AppPapeleriaRoute = AppPapeleriaRouteImport.update({
  id: '/papeleria',
  path: '/papeleria',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordatoriosRoute = AppRecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProductoresIndexRoute = AppProductoresIndexRouteImport.update({
  id: '/productores/',
  path: '/productores/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductoresIdRoute = AppProductoresIdRouteImport.update({
  id: '/productores/$id',
  path: '/productores/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductoresNuevoRoute = AppProductoresNuevoRouteImport.update({
  id: '/productores/nuevo',
  path: '/productores/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/avisos': typeof AppAvisosRoute
  '/citas': typeof AppCitasRoute
  '/duplicados': typeof AppDuplicadosRoute
  '/embudo': typeof AppEmbudoRoute
  '/equipo': typeof AppEquipoRoute
  '/exportar': typeof AppExportarRoute
  '/grupos': typeof AppGruposRoute
  '/guia': typeof AppGuiaRoute
  '/papeleria': typeof AppPapeleriaRoute
  '/recordatorios': typeof AppRecordatoriosRoute
  '/productores/$id': typeof AppProductoresIdRoute
  '/productores/nuevo': typeof AppProductoresNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/productores/': typeof AppProductoresIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/avisos': typeof AppAvisosRoute
  '/citas': typeof AppCitasRoute
  '/duplicados': typeof AppDuplicadosRoute
  '/embudo': typeof AppEmbudoRoute
  '/equipo': typeof AppEquipoRoute
  '/exportar': typeof AppExportarRoute
  '/grupos': typeof AppGruposRoute
  '/guia': typeof AppGuiaRoute
  '/papeleria': typeof AppPapeleriaRoute
  '/recordatorios': typeof AppRecordatoriosRoute
  '/': typeof AppIndexRoute
  '/productores/$id': typeof AppProductoresIdRoute
  '/productores/nuevo': typeof AppProductoresNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/productores': typeof AppProductoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/avisos': typeof AppAvisosRoute
  '/_app/citas': typeof AppCitasRoute
  '/_app/duplicados': typeof AppDuplicadosRoute
  '/_app/embudo': typeof AppEmbudoRoute
  '/_app/equipo': typeof AppEquipoRoute
  '/_app/exportar': typeof AppExportarRoute
  '/_app/grupos': typeof AppGruposRoute
  '/_app/guia': typeof AppGuiaRoute
  '/_app/papeleria': typeof AppPapeleriaRoute
  '/_app/recordatorios': typeof AppRecordatoriosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/productores/$id': typeof AppProductoresIdRoute
  '/_app/productores/nuevo': typeof AppProductoresNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/productores/': typeof AppProductoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/avisos'
    | '/citas'
    | '/duplicados'
    | '/embudo'
    | '/equipo'
    | '/exportar'
    | '/grupos'
    | '/guia'
    | '/papeleria'
    | '/recordatorios'
    | '/productores/$id'
    | '/productores/nuevo'
    | '/api/auth/$'
    | '/productores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/avisos'
    | '/citas'
    | '/duplicados'
    | '/embudo'
    | '/equipo'
    | '/exportar'
    | '/grupos'
    | '/guia'
    | '/papeleria'
    | '/recordatorios'
    | '/'
    | '/productores/$id'
    | '/productores/nuevo'
    | '/api/auth/$'
    | '/productores'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/avisos'
    | '/_app/citas'
    | '/_app/duplicados'
    | '/_app/embudo'
    | '/_app/equipo'
    | '/_app/exportar'
    | '/_app/grupos'
    | '/_app/guia'
    | '/_app/papeleria'
    | '/_app/recordatorios'
    | '/_app/'
    | '/_app/productores/$id'
    | '/_app/productores/nuevo'
    | '/api/auth/$'
    | '/_app/productores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avisos': {
      id: '/_app/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AppAvisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/citas': {
      id: '/_app/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof AppCitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/duplicados': {
      id: '/_app/duplicados'
      path: '/duplicados'
      fullPath: '/duplicados'
      preLoaderRoute: typeof AppDuplicadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/embudo': {
      id: '/_app/embudo'
      path: '/embudo'
      fullPath: '/embudo'
      preLoaderRoute: typeof AppEmbudoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipo': {
      id: '/_app/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AppEquipoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exportar': {
      id: '/_app/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof AppExportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos': {
      id: '/_app/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AppGruposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guia': {
      id: '/_app/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof AppGuiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/papeleria': {
      id: '/_app/papeleria'
      path: '/papeleria'
      fullPath: '/papeleria'
      preLoaderRoute: typeof AppPapeleriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recordatorios': {
      id: '/_app/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof AppRecordatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/productores/': {
      id: '/_app/productores/'
      path: '/productores'
      fullPath: '/productores/'
      preLoaderRoute: typeof AppProductoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/productores/$id': {
      id: '/_app/productores/$id'
      path: '/productores/$id'
      fullPath: '/productores/$id'
      preLoaderRoute: typeof AppProductoresIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/productores/nuevo': {
      id: '/_app/productores/nuevo'
      path: '/productores/nuevo'
      fullPath: '/productores/nuevo'
      preLoaderRoute: typeof AppProductoresNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAvisosRoute: typeof AppAvisosRoute
  AppCitasRoute: typeof AppCitasRoute
  AppDuplicadosRoute: typeof AppDuplicadosRoute
  AppEmbudoRoute: typeof AppEmbudoRoute
  AppEquipoRoute: typeof AppEquipoRoute
  AppExportarRoute: typeof AppExportarRoute
  AppGruposRoute: typeof AppGruposRoute
  AppGuiaRoute: typeof AppGuiaRoute
  AppPapeleriaRoute: typeof AppPapeleriaRoute
  AppRecordatoriosRoute: typeof AppRecordatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProductoresIdRoute: typeof AppProductoresIdRoute
  AppProductoresNuevoRoute: typeof AppProductoresNuevoRoute
  AppProductoresIndexRoute: typeof AppProductoresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvisosRoute: AppAvisosRoute,
  AppCitasRoute: AppCitasRoute,
  AppDuplicadosRoute: AppDuplicadosRoute,
  AppEmbudoRoute: AppEmbudoRoute,
  AppEquipoRoute: AppEquipoRoute,
  AppExportarRoute: AppExportarRoute,
  AppGruposRoute: AppGruposRoute,
  AppGuiaRoute: AppGuiaRoute,
  AppPapeleriaRoute: AppPapeleriaRoute,
  AppRecordatoriosRoute: AppRecordatoriosRoute,
  AppIndexRoute: AppIndexRoute,
  AppProductoresIdRoute: AppProductoresIdRoute,
  AppProductoresNuevoRoute: AppProductoresNuevoRoute,
  AppProductoresIndexRoute: AppProductoresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
